# title: eep # The title of the blog
author: Anthony Tran # Your name 
email: studio@anthonytran.info # your email shown in the footer
url: http://anthonytran.info/ # this is your site's root address.
# description: > # this means to ignore newlines until "show_excerpts:"
  # anthony tran is a technologist, writer, and artist, currently attending the european graduate school for philosophy and art.
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  # avatar_url: "https://i.loli.net/2019/08/26/JzCLhDWPEybZr2T.jpg" # avatar in about page
  about_you: anthony tran is a technologist, writer, and artist, currently attending the european graduate school for philosophy and art. i grew up in a hotel in times square and most recently moved out of los angeles. extremely online in a specific way but probably better face-to-face. # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    # twitter: 
    # github:  huangyz0918
    # rss: RSS
    # dribbble: 
    # facebook: huangyz0918
    # flickr:   
    # instagram: 
    # linkedin: yizheng-huang
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
theme: moving # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
