title: Anthony Tran # The title of the blog
author: Anthony Tran # Your name 
email: studio@anthonytran.info # your email shown in the footer
url: https://anthonytran.info/ # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  Anthony Tran works across technology, publication, and art. ↴
favicon: "./favicon.ico" # set the favicon of the site 
google_analytics: UA-36861842-1

show_excerpts: true # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  date_format: "%b %d" # date format of posts in home page
  back_to: "Back" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    # twitter: 
    # github:  huangyz0918
    # rss: RSS
    # dribbble: 
    # facebook: huangyz0918
    # flickr:   
    # instagram: 
    # linkedin: yizheng-huang
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
# theme: moving # note, please use huangyz0918/moving if you want to publish to Github Pages.
remote_theme: huangyz0918/moving

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gallery-generator

gallery:
  sort_field: "title"
  title_prefix: ""
  galleries:
    20230807_summer_away:
      best_image: 000492610034.jpg
    20240426_bday_film:
      info:
        desc: All photos here by Alex Free (@alexfree_hi)
    20240426_bday_digitals:
      info:
        desc: All photos here by Alex Free (@alexfree_hi)
    20240428_bday_b&w:
      best_image: 002.jpg